# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
#   whenever we push a change to the master branch, we want the following actions to run
    branches: [ master ]

jobs:
  build:
# run the action on a vps if you choose self-hosted
    runs-on: self-hosted

    strategy:
      matrix:
#       We can choose the run the jobs for all of the following versions
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
#         Install nodejs. We only need to install in our case
# ci will do clean install
# i will do install

    - run: npm i
#     run a build script if we have that available to us
# for nodejs, this is the package.json file so it will install all of the packages
    - run: npm run build --if-present
#     run any test scripts in package.json
    - run: npm test
